packages:
  - apps/**
  - packages/**
  - tooling/**
catalog:
  "@tanstack/react-query": ^5.79.0
  "@trpc/client": ^11.0.0-rc.666
  "@trpc/react-query": ^11.0.0-rc.666
  "@trpc/server": ^11.0.0-rc.666
  "@turbo/gen": ^2.5.8
  eslint: ^9.9.0
  lucide-react: ^0.462.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.17
  turbo: ^2.5.8
  typescript: ^5.7.3
  superjson: ^2.2.2
  zod: ^3.24.2
catalogs:
  react:
    next: ^15.3.3
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
