export const presenceOptions = [
  "Throwing mfs off the train",
  "Throwing mfs at another mfs",
  "Jumping on a pole",
  "Whooping mfs",
  "Never half ass",
  "Invading Gotham City",
  "Ridin' a bicycle w/o a saddle",
  "Browsing your mom's Facebook",
  "Browsing your browser history",
  "Ridin' your mum",
  "Blowing mfs (up)",
  "Listening to enemies' screams",
  "Watching your mum",
];
