export const presenceOptions = [
  "Throwing mfs off the train",
  "Throwing mfs at another mfs",
  "Jumping on a pole",
  "Whooping mfs",
  "Never half ass",
  "Invading Gotham City",
  "Ridin' a bicycle",
  "Browsing your mom's Facebook",
  "Browsing your browser history",
  "Ridin' your mum",
  "Blowwing mfs up",
  "Listening to enemies scream",
  "Watching your mum",
];
